import type { Concept, ConceptGroup } from './model'
import extra from './extra.json'

export const GROUP_LABEL: Record<ConceptGroup, string> = {
  fundacao: 'Fundação',
  probabilidade: 'Probabilidade e distribuições',
  estimacao: 'Estimação e testes',
  causalidade: 'Causalidade e vieses',
  'ia-tarefas': 'Métricas por tarefa de IA',
  'ia-generativa': 'IA generativa e LLMs',
  'ia-incerteza': 'Informação e incerteza em IA',
  'ia-treino': 'Fine-tuning, alinhamento e treino',
  'imagem-treino': 'Difusão e ajuste de modelos de imagem',
  'imagem-avaliacao': 'Avaliar imagens geradas',
  'audio-geracao': 'Áudio e fala gerados',
  'midia-sintetica': 'Autenticidade e riscos da mídia sintética',
  taxas: 'Taxas da matriz',
  resumo: 'Métricas-resumo',
  curvas: 'Curvas e ranking',
  decisao: 'Decisão e probabilidade',
  validacao: 'Validação e benchmarks',
  inferencia: 'Inferência e incerteza',
  dados: 'Dados e generalização',
}

/** Ordem de estudo sugerida: do vocabulário básico à decisão, inferência, causalidade e generalização. */
export const GROUP_ORDER: ConceptGroup[] = ['fundacao', 'probabilidade', 'taxas', 'resumo', 'estimacao', 'inferencia', 'curvas', 'decisao', 'causalidade', 'validacao', 'dados', 'ia-tarefas', 'ia-generativa', 'ia-incerteza', 'ia-treino', 'imagem-treino', 'imagem-avaliacao', 'audio-geracao', 'midia-sintetica']

export const GROUP_DESC: Record<ConceptGroup, string> = {
  fundacao: 'A tabela 2×2, o gabarito e os dois tipos de erro.',
  probabilidade: 'Variáveis aleatórias, binomial, normal e por que médias de amostras se comportam bem.',
  taxas: 'As taxas condicionais que saem da matriz e o papel da prevalência.',
  resumo: 'Como resumir a matriz num número — e o que cada resumo esconde.',
  estimacao: 'Estimar uma métrica com incerteza: verossimilhança, bootstrap, Bayes, testes pareados.',
  inferencia: 'p-valor, intervalos, poder e as armadilhas de comparar muitas coisas.',
  curvas: 'Quando o limiar varia: ROC, PR, AUC e ranking.',
  decisao: 'Custos, limiar ótimo, calibração e utilidade.',
  causalidade: 'Por que associação não basta e como vieses de seleção enganam.',
  validacao: 'Validação cruzada, comparação de modelos, rótulos ruidosos e benchmarks.',
  dados: 'Vazamento, sobreajuste, mudança de distribuição, justiça e Goodhart.',
  'ia-tarefas': 'Regressão, ranking e recomendação, detecção e segmentação, fala, multirrótulo e agrupamento.',
  'ia-generativa': 'Perplexidade, BLEU/ROUGE, pass@k, LLM como juiz, Elo, FID, RAG e alucinação.',
  'ia-incerteza': 'Entropia, KL, predição conformal, drift, barras de erro em avaliações e robustez.',
  'ia-treino': 'Como avaliar fine-tuning e alinhamento: LoRA, instruções, esquecimento, RLHF e DPO, recompensa, contaminação, escala e harnesses.',
  'imagem-treino': 'Difusão latente, guidance, LoRA e DreamBooth para imagens, ControlNet e memorização de dados de treino.',
  'imagem-avaliacao': 'KID e CMMD, precisão e recall gerativos, LPIPS/SSIM, preferência humana e alinhamento texto–imagem.',
  'audio-geracao': 'MOS e MUSHRA, FAD e CLAP, PESQ/STOI/SI-SDR, similaridade de locutor, MOS previsto e codecs neurais.',
  'midia-sintetica': 'EER e curvas DET, detectores de mídia sintética, marca d’água, proveniência e vieses de representação.',
}

const BASE_CONCEPTS: Concept[] = [
  // ——— Fundação ———
  {
    id: 'matriz-confusao', name: 'Matriz de confusão', aka: ['tabela de contingência 2×2', 'confusion matrix'], group: 'fundacao',
    formula: 'N = TP + FP + FN + TN',
    definition: 'Tabela que cruza a classe prevista com a classe de referência. No caso binário tem quatro células: verdadeiros positivos (TP), falsos positivos (FP), falsos negativos (FN) e verdadeiros negativos (TN). Toda métrica de classificação por limiar é uma função dessas quatro contagens.',
    intuition: 'É a distribuição conjunta de (previsão, verdade). Uma métrica-resumo sempre joga fora parte dela — a pergunta é qual parte você aceita perder.',
    origin: 'A tabela 2×2 aparece em 1884 na verificação das previsões de tornado de J. P. Finley e na resposta de C. S. Peirce. O nome "matriz de confusão" vem da psicologia experimental, onde se registrava quais estímulos eram confundidos com quais. Murphy & Winkler (1987) formalizam a tabela como a distribuição conjunta de previsão e observação.',
    pitfalls: [
      'Reportar só uma métrica sem a tabela completa impede o leitor de recalcular qualquer outra.',
      'As contagens dependem da prevalência da amostra de teste; taxas condicionais (TPR, FPR) não dependem, preditivas (PPV, NPV) sim.',
    ],
    related: ['gold-standard', 'acuracia', 'sensibilidade', 'precisao'],
    refIds: ['peirce-1884', 'murphy-1996', 'murphy-winkler-1987', 'stard-2015', 'sokolova-lapalme-2009'],
    lab: true,
  },
  {
    id: 'gold-standard', name: 'Gold standard / conjunto de referência', aka: ['gabarito', 'ground truth', 'test collection', 'reference standard'], group: 'fundacao',
    definition: 'O rótulo contra o qual a previsão é comparada. Em recuperação da informação são os julgamentos de relevância; em medicina, o exame de referência; em ML, o test set anotado.',
    intuition: 'A matriz de confusão mede concordância com o gabarito, não com a verdade. Se o gabarito erra, a métrica herda o erro — e pode inverter rankings.',
    origin: 'O paradigma Cranfield (Cleverdon, 1962–66) fixa coleção + consultas + julgamentos + métrica, o ancestral direto do benchmark. A medicina formaliza o problema do "reference standard imperfeito" (Rutjes et al., 2007; QUADAS-2).',
    pitfalls: [
      'Tratar o gabarito como verdade absoluta: anotadores discordam e test sets famosos têm erros de rótulo (Northcutt et al., 2021).',
      'Viés de verificação: só confirmar com o padrão de referência os casos que o teste marcou como positivos.',
      'Desacordo entre anotadores pode ser sinal (ambiguidade real), não ruído (Aroyo & Welty, 2015).',
    ],
    related: ['kappa', 'rotulos-ruidosos', 'benchmarks'],
    refIds: ['cleverdon-1962', 'cleverdon-1966', 'voorhees-harman-2005', 'rutjes-2007', 'whiting-2011', 'aroyo-welty-2015', 'northcutt-2021'],
  },
  {
    id: 'erros-tipo', name: 'Erros tipo I e tipo II', aka: ['falso alarme', 'omissão', 'α e β'], group: 'fundacao',
    formula: 'α = P(rejeitar H₀ | H₀ verdadeira) = FPR\nβ = P(aceitar H₀ | H₁ verdadeira) = 1 − TPR',
    definition: 'No teste de hipóteses, erro tipo I é declarar efeito quando não há (falso positivo) e erro tipo II é não detectar um efeito real (falso negativo).',
    intuition: 'Não dá para zerar os dois ao mesmo tempo com os mesmos dados: mover o limiar troca um pelo outro. A curva ROC é exatamente o desenho dessa troca.',
    origin: 'Neyman & Pearson (1933) definem os dois erros e provam que o teste de razão de verossimilhança maximiza o poder (1 − β) para um α fixo — o lema de Neyman–Pearson.',
    pitfalls: ['Confundir α (taxa condicional à hipótese nula) com a probabilidade de a hipótese ser verdadeira dado o resultado — é o mesmo erro de confundir FPR com 1 − PPV.'],
    related: ['razao-verossimilhanca', 'roc', 'limiar-custo'],
    refIds: ['neyman-pearson-1933', 'wald-1950', 'berger-1985'],
  },

  // ——— Taxas ———
  {
    id: 'sensibilidade', name: 'Sensibilidade / recall / TPR', aka: ['revocação', 'hit rate', 'true positive rate', 'poder'], group: 'taxas',
    formula: 'TPR = TP / (TP + FN)',
    definition: 'Fração dos positivos reais que o classificador detecta.',
    intuition: 'Condicionada à verdade: "dos que realmente são, quantos eu peguei?". Não depende da prevalência.',
    origin: 'Três tradições chegam ao mesmo número: "recall" na recuperação da informação (Kent et al., 1955; Cleverdon), "sensibilidade" na medicina (termo vindo da sorologia do início do século XX e popularizado por Yerushalmy, 1947; ver Binney et al., 2021) e "hit rate" na detecção de sinais (Tanner & Swets, 1954).',
    pitfalls: ['Sozinha é trivial de maximizar: dizer "positivo" para tudo dá TPR = 1.'],
    related: ['especificidade', 'precisao', 'f-measure', 'roc'],
    refIds: ['yerushalmy-1947', 'binney-2021', 'kent-1955', 'cleverdon-1966', 'tanner-swets-1954', 'altman-bland-1994a'],
    lab: true,
  },
  {
    id: 'especificidade', name: 'Especificidade / TNR', aka: ['true negative rate', 'seletividade', 'correct rejection rate'], group: 'taxas',
    formula: 'TNR = TN / (TN + FP) = 1 − FPR',
    definition: 'Fração dos negativos reais corretamente classificados como negativos.',
    intuition: 'O par natural da sensibilidade. Juntas descrevem o teste sem depender de quantos positivos existem na população.',
    origin: 'O par sensibilidade/especificidade vem da sorologia do início do século XX (testes de sífilis); Yerushalmy (1947) o levou à avaliação de leitores de raio-X de tuberculose, onde se consolidou (Binney, Hyde & Bossuyt, 2021).',
    pitfalls: ['Em recuperação da informação quase não é usada: TN é astronômico (todo documento irrelevante não recuperado), então a especificidade fica ≈ 1 para qualquer sistema.'],
    related: ['sensibilidade', 'fpr', 'acuracia-balanceada'],
    refIds: ['yerushalmy-1947', 'binney-2021', 'altman-bland-1994a', 'pepe-2003'],
    lab: true,
  },
  {
    id: 'fpr', name: 'Taxa de falso positivo / FPR', aka: ['false alarm rate', 'fall-out', '1 − especificidade'], group: 'taxas',
    formula: 'FPR = FP / (FP + TN)',
    definition: 'Fração dos negativos reais que o classificador marca como positivos. É o eixo X da curva ROC.',
    intuition: 'Na detecção de sinais é o "alarme falso": o radar apitou e não havia avião.',
    origin: 'Tanner & Swets (1954) e Green & Swets (1966) tratam hit rate × false-alarm rate como as duas coordenadas de um observador. Em IR aparece como "fallout" (Salton).',
    pitfalls: ['FPR baixo não significa poucos alarmes falsos em números absolutos quando os negativos são a imensa maioria — olhe PPV também.'],
    related: ['especificidade', 'roc', 'erros-tipo'],
    refIds: ['tanner-swets-1954', 'green-swets-1966', 'salton-mcgill-1983', 'fawcett-2006'],
    lab: true,
  },
  {
    id: 'precisao', name: 'Precisão / PPV', aka: ['precision', 'valor preditivo positivo', 'positive predictive value'], group: 'taxas',
    formula: 'PPV = TP / (TP + FP)',
    definition: 'Fração das previsões positivas que estão corretas.',
    intuition: 'Condicionada à previsão: "quando eu digo que é, quantas vezes acerto?". Depende fortemente da prevalência.',
    origin: 'Em IR é a fração do recuperado que é relevante (Kent et al., 1955; Cleverdon). Em medicina é o valor preditivo positivo, discutido desde os anos 1950 e popularizado por Altman & Bland (1994).',
    pitfalls: [
      'O mesmo teste tem PPV alto num hospital de referência e baixo em rastreamento populacional — a prevalência mudou, o teste não.',
      'Indefinida quando o classificador não prevê nenhum positivo (0/0).',
    ],
    related: ['prevalencia-bayes', 'sensibilidade', 'curva-pr', 'f-measure'],
    refIds: ['kent-1955', 'cleverdon-1966', 'van-rijsbergen-1979', 'altman-bland-1994b', 'manning-2008'],
    lab: true,
  },
  {
    id: 'prevalencia-bayes', name: 'Prevalência e teorema de Bayes', aka: ['taxa-base', 'base rate', 'NPV', 'valor preditivo negativo'], group: 'taxas',
    formula: 'PPV = TPR·π / (TPR·π + FPR·(1 − π))\nNPV = TNR·(1 − π) / (TNR·(1 − π) + (1 − TPR)·π)',
    definition: 'Os valores preditivos são a probabilidade a posteriori obtida combinando as taxas do teste (TPR, FPR) com a prevalência π.',
    intuition: 'Com π = 1% e um teste com 99% de sensibilidade e especificidade, metade dos positivos é falsa. A "falácia da taxa-base" é ignorar π.',
    origin: 'É o teorema de Bayes aplicado à tabela 2×2. A discussão clínica de valores preditivos dependentes da prevalência é consolidada na série "Diagnostic tests" do BMJ (Altman & Bland, 1994).',
    pitfalls: ['Comparar PPV entre estudos com prevalências diferentes.', 'Treinar com dados balanceados artificialmente e reportar PPV como se valesse na população real.'],
    related: ['precisao', 'razao-verossimilhanca', 'curva-pr'],
    refIds: ['altman-bland-1994b', 'yerushalmy-1947', 'pepe-2003', 'zhou-2011'],
    lab: true,
  },
  {
    id: 'razao-verossimilhanca', name: 'Razões de verossimilhança', aka: ['likelihood ratio', 'LR+', 'LR−'], group: 'taxas',
    formula: 'LR+ = TPR / FPR\nLR− = (1 − TPR) / TNR\nchance posterior = chance prévia × LR',
    definition: 'Quanto um resultado positivo (ou negativo) multiplica a chance de a condição estar presente.',
    intuition: 'É a forma "independente de prevalência" de falar em poder preditivo: o teste fornece o LR, a população fornece a chance prévia.',
    origin: 'A razão de verossimilhança é o objeto central do lema de Neyman–Pearson (1933) e da teoria de detectabilidade de sinais (Peterson, Birdsall & Fox, 1954): o detector ótimo compara LR(x) com um limiar.',
    pitfalls: ['LR+ explode quando FPR → 0 em amostras pequenas; use intervalos de confiança.'],
    related: ['erros-tipo', 'prevalencia-bayes', 'limiar-custo', 'roc'],
    refIds: ['neyman-pearson-1933', 'peterson-birdsall-fox-1954', 'green-swets-1966', 'zhou-2011'],
    lab: true,
  },

  // ——— Métricas-resumo ———
  {
    id: 'acuracia', name: 'Acurácia', aka: ['accuracy', 'taxa de acerto', 'percent correct'], group: 'resumo',
    formula: 'ACC = (TP + TN) / N',
    definition: 'Fração de todas as previsões que estão corretas.',
    intuition: 'Soma acertos de classes diferentes como se valessem o mesmo e pondera cada classe pela sua frequência. Com classes raras, mede basicamente a classe comum.',
    origin: 'O paradoxo é de 1884: Finley anunciou 96,6% de acerto em previsões de tornado; Gilbert observou que prever "sem tornado" sempre daria 98,2%. Peirce respondeu no mesmo ano propondo uma medida de habilidade que desconta o acaso (Murphy, 1996).',
    pitfalls: [
      'Com 1% de positivos, um classificador constante tem 99% de acurácia.',
      'Não é "própria" para comparar indutores quando custos e distribuição de classes variam (Provost, Fawcett & Kohavi, 1998).',
    ],
    related: ['acuracia-balanceada', 'kappa', 'youden', 'mcc'],
    refIds: ['murphy-1996', 'peirce-1884', 'provost-1998', 'he-garcia-2009'],
    lab: true,
  },
  {
    id: 'f-measure', name: 'F-measure (F1, Fβ)', aka: ['F-score', 'medida E de van Rijsbergen', 'Dice'], group: 'resumo',
    formula: 'Fβ = (1 + β²)·P·R / (β²·P + R)\nF1 = 2TP / (2TP + FP + FN)\nE = 1 − F',
    definition: 'Média harmônica ponderada de precisão e recall. β > 1 dá mais peso ao recall.',
    intuition: 'Não usa TN. Faz sentido quando os negativos são mal definidos ou infinitos (busca, extração de entidades) e o que importa é a classe positiva.',
    origin: 'Van Rijsbergen (1979, cap. 7) deriva a medida E a partir de uma teoria de medição da efetividade; F = 1 − E e o β² vem da escolha do ponto onde o usuário troca recall por precisão (Sasaki, 2007). Entrou no PLN pela MUC-4 (Chinchor, 1992). F1 é algebricamente o coeficiente de Dice (1945).',
    pitfalls: [
      'Ignora TN: dois classificadores com F1 igual podem ser muito diferentes na classe negativa (Powers, 2011).',
      'Não é uma média de P e R com pesos fixos — os pesos efetivos dependem do próprio classificador (Hand & Christen, 2018).',
      'O limiar que maximiza F1 é F1*/2 em termos de probabilidade calibrada, não 0,5 (Lipton et al., 2014).',
      'Média de F1 por fold ≠ F1 das contagens somadas (Forman & Scholz, 2010).',
    ],
    related: ['precisao', 'sensibilidade', 'jaccard', 'mcc', 'macro-micro'],
    refIds: ['van-rijsbergen-1979', 'chinchor-1992', 'sasaki-2007', 'dice-1945', 'powers-2011', 'hand-christen-2018', 'lipton-2014', 'forman-scholz-2010'],
    lab: true,
  },
  {
    id: 'jaccard', name: 'Jaccard / IoU', aka: ['intersection over union', 'critical success index', 'threat score'], group: 'resumo',
    formula: 'J = TP / (TP + FP + FN)\nF1 = 2J / (1 + J)',
    definition: 'Tamanho da interseção entre previsto e real dividido pelo tamanho da união.',
    intuition: 'Monotonicamente equivalente ao F1 — ordenam classificadores igual, mas J é mais severo com erros.',
    origin: 'Jaccard (1912) para comparar a flora de regiões alpinas; Dice (1945) propõe a versão 2|A∩B|/(|A|+|B|). Na meteorologia o mesmo número é o "critical success index", já usado por Gilbert em 1884.',
    pitfalls: ['Como F1, ignora TN e é instável com poucos positivos.'],
    related: ['f-measure'],
    refIds: ['jaccard-1912', 'dice-1945', 'murphy-1996', 'maier-hein-2024'],
    lab: true,
  },
  {
    id: 'acuracia-balanceada', name: 'Acurácia balanceada', aka: ['balanced accuracy', 'macro-recall'], group: 'resumo',
    formula: 'BA = (TPR + TNR) / 2',
    definition: 'Média do recall de cada classe.',
    intuition: 'É a acurácia que você teria se o test set fosse balanceado. Um classificador constante tira exatamente 0,5.',
    origin: 'Usada há tempos como alternativa à acurácia em dados desbalanceados; Brodersen et al. (2010) propuseram sua distribuição a posteriori para obter intervalos de confiança. É (J + 1)/2, onde J é o índice de Youden.',
    pitfalls: ['Não diz nada sobre precisão: pode ser alta com PPV péssimo quando positivos são raros.'],
    related: ['acuracia', 'youden', 'macro-micro'],
    refIds: ['brodersen-2010', 'chicco-2021', 'grandini-2020'],
    lab: true,
  },
  {
    id: 'youden', name: 'Índice de Youden / Peirce skill score', aka: ['informedness', 'Hanssen–Kuipers', 'true skill statistic', 'J'], group: 'resumo',
    formula: 'J = TPR − FPR = TPR + TNR − 1',
    definition: 'Distância vertical do ponto de operação até a diagonal da ROC.',
    intuition: 'Probabilidade de a decisão ser "informada" em vez de chute: 0 = aleatório, 1 = perfeito, negativo = pior que o acaso.',
    origin: 'Peirce (1884) propôs exatamente essa medida para as previsões de Finley. Youden (1950) a redescobriu para testes diagnósticos; Powers a chamou de "informedness" e difundiu o termo (2011).',
    pitfalls: ['Maximizar J assume que FP e FN custam o mesmo após normalizar pela prevalência — raramente é o caso clínico.'],
    related: ['acuracia-balanceada', 'roc', 'mcc'],
    refIds: ['peirce-1884', 'youden-1950', 'powers-2011', 'murphy-1996'],
    lab: true,
  },
  {
    id: 'mcc', name: 'MCC (correlação de Matthews)', aka: ['coeficiente phi', 'φ'], group: 'resumo',
    formula: 'MCC = (TP·TN − FP·FN) / √((TP+FP)(TP+FN)(TN+FP)(TN+FN))\nMCC² = informedness × markedness',
    definition: 'Correlação de Pearson entre o vetor previsto e o real, em [−1, 1].',
    intuition: 'Só é alto se as quatro células forem boas ao mesmo tempo. É simétrico: trocar qual classe é "positiva" não muda o valor.',
    origin: 'Matthews (1975), em bioquímica (predição de estrutura secundária de proteínas); é o coeficiente φ de Pearson para tabelas 2×2. Chicco & Jurman (2020) argumentam que deve substituir F1 e acurácia em classificação binária.',
    pitfalls: [
      'Indefinido quando alguma margem é zero (ex.: nunca prevê positivo).',
      'Não é a métrica certa se só a classe positiva importa e TN é mal definido (IR).',
    ],
    related: ['f-measure', 'kappa', 'youden'],
    refIds: ['matthews-1975', 'chicco-jurman-2020', 'powers-2011', 'chicco-2021', 'delgado-tibau-2019'],
    lab: true,
  },
  {
    id: 'kappa', name: 'Kappa de Cohen / Heidke skill score', aka: ['κ', 'concordância corrigida pelo acaso'], group: 'resumo',
    formula: 'κ = (p₀ − pₑ) / (1 − pₑ)\npₑ = [(TP+FP)(TP+FN) + (FN+TN)(FP+TN)] / N²',
    definition: 'Concordância observada descontada da concordância esperada por acaso dadas as margens.',
    intuition: 'Nasceu para medir concordância entre anotadores, não entre modelo e verdade. É a primeira pergunta sobre um gold standard: humanos concordam entre si?',
    origin: 'Heidke (1926) propôs a mesma forma para previsões meteorológicas; Cohen (1960) para codificadores em psicologia. Fleiss (1971) generaliza para vários avaliadores; Landis & Koch (1977) criam a escala qualitativa.',
    pitfalls: [
      'Paradoxos: κ baixo com concordância alta quando as margens são desbalanceadas (Feinstein & Cicchetti, 1990). AC1 de Gwet tenta corrigir.',
      'A escala "substancial/quase perfeito" é arbitrária.',
      'Como métrica de classificador, pode discordar do MCC de forma enganosa (Delgado & Tibau, 2019).',
      'Quando TN é indefinido, F-measure entre anotadores aproxima κ (Hripcsak & Rothschild, 2005).',
    ],
    related: ['gold-standard', 'mcc', 'rotulos-ruidosos'],
    refIds: ['heidke-1926', 'cohen-1960', 'fleiss-1971', 'landis-koch-1977', 'feinstein-cicchetti-1990', 'gwet-2014', 'hripcsak-rothschild-2005', 'artstein-poesio-2008', 'krippendorff-2018'],
    lab: true,
  },

  // ——— Curvas ———
  {
    id: 'd-linha', name: 'd′ e critério (detecção de sinais)', aka: ["d-prime", 'sensibilidade discriminativa', 'viés de resposta', 'c', 'β'], group: 'curvas',
    formula: "d′ = z(TPR) − z(FPR)\nc = −[z(TPR) + z(FPR)] / 2\nAUC = Φ(d′/√2)  (binormal, variâncias iguais)",
    definition: 'Separa duas coisas que a matriz mistura: quão separáveis são as distribuições de sinal e ruído (d′) e onde o observador colocou o limiar (c).',
    intuition: 'Dois classificadores com a mesma d′ mas limiares diferentes têm matrizes de confusão muito diferentes — e são o mesmo detector.',
    origin: 'Tanner & Swets (1954) e Green & Swets (1966), herdando a teoria de radar de Peterson, Birdsall & Fox (1954). Macmillan & Creelman é o guia prático.',
    pitfalls: ['A fórmula assume scores normais com variâncias iguais; se a ROC em escala z não tiver inclinação 1, use modelos com variâncias diferentes.'],
    related: ['roc', 'auc', 'erros-tipo'],
    refIds: ['tanner-swets-1954', 'green-swets-1966', 'macmillan-creelman-2005', 'peterson-birdsall-fox-1954'],
    lab: true,
  },
  {
    id: 'roc', name: 'Curva ROC', aka: ['receiver operating characteristic', 'espaço ROC'], group: 'curvas',
    formula: 'ROC(t) = (FPR(t), TPR(t)),  t ∈ ℝ',
    definition: 'Curva de todos os pares (FPR, TPR) obtidos variando o limiar sobre o score.',
    intuition: 'Descreve o detector, não uma decisão. Cada ponto é uma matriz de confusão possível; escolher o ponto é escolher custos e prevalência.',
    origin: 'Nasce na teoria de radar (Peterson, Birdsall & Fox, 1954), passa à psicofísica (Green & Swets, 1966), à radiologia (Metz, 1978) e ao ML (Bradley, 1997; Fawcett, 2006).',
    pitfalls: [
      'Parece otimista com classes muito desbalanceadas: FPR pequeno ainda pode significar muitos FP em números absolutos (Saito & Rehmsmeier, 2015).',
      'O melhor classificador para uma condição operacional é o que está no casco convexo naquele ponto, não o de maior AUC.',
    ],
    related: ['auc', 'curva-pr', 'd-linha', 'limiar-custo', 'fpr'],
    refIds: ['peterson-birdsall-fox-1954', 'green-swets-1966', 'metz-1978', 'swets-1988', 'zweig-campbell-1993', 'altman-bland-1994c', 'fawcett-2006'],
    lab: true,
  },
  {
    id: 'auc', name: 'AUC (área sob a ROC)', aka: ['AUROC', 'estatística C', 'Mann–Whitney U normalizada'], group: 'curvas',
    formula: 'AUC = P(s₊ > s₋) + ½·P(s₊ = s₋)',
    definition: 'Probabilidade de um positivo aleatório receber score maior que um negativo aleatório.',
    intuition: 'Mede a qualidade do ranking, integrada sobre todos os limiares. Não diz nada sobre calibração nem sobre o limiar que você vai usar.',
    origin: 'Hanley & McNeil (1982) mostram a equivalência com Mann–Whitney e dão o erro-padrão; DeLong et al. (1988) o teste para AUCs correlacionadas; Bradley (1997) leva ao ML; Hand & Till (2001) generalizam para multiclasse.',
    pitfalls: [
      'Hand (2009): a AUC equivale a uma perda esperada com distribuição de custos que depende do próprio classificador — comparar AUCs é comparar com réguas diferentes.',
      'Curvas que se cruzam podem ter AUC igual e ser boas em regiões opostas.',
      'Pouco sensível a melhorias na região de FPR baixo, que muitas vezes é a única que importa.',
    ],
    related: ['roc', 'curva-pr', 'comparacao-estatistica', 'calibracao'],
    refIds: ['hanley-mcneil-1982', 'delong-1988', 'bradley-1997', 'hand-till-2001', 'hand-2009', 'krzanowski-hand-2009', 'ferri-2009'],
    lab: true,
  },
  {
    id: 'curva-pr', name: 'Curva precisão-recall e AP', aka: ['PR curve', 'average precision', 'AUPRC', 'MAP'], group: 'curvas',
    formula: 'AP = Σₙ (Rₙ − Rₙ₋₁)·Pₙ\nbaseline de precisão = π',
    definition: 'Precisão em função do recall ao variar o limiar. Average precision resume a curva; MAP é a média de AP sobre consultas.',
    intuition: 'Foca na classe positiva e reage à prevalência: com positivos raros, mostra o custo real dos falsos positivos que a ROC esconde.',
    origin: 'Curvas precisão-recall interpoladas são o padrão da avaliação SMART/TREC (Salton & McGill, 1983; Manning et al., 2008). Davis & Goadrich (2006) provam a correspondência com ROC; Saito & Rehmsmeier (2015) mostram a vantagem em dados desbalanceados.',
    pitfalls: [
      'Interpolar linearmente entre pontos no espaço PR é errado e superestima a área (Davis & Goadrich, 2006).',
      'Estimadores diferentes de AUPRC dão números diferentes (Boyd et al., 2013).',
      'A área PR não tem baseline linear nem interpretação de probabilidade; PR-Gain corrige isso (Flach & Kull, 2015).',
    ],
    related: ['roc', 'precisao', 'prevalencia-bayes', 'ranking-ir'],
    refIds: ['salton-mcgill-1983', 'manning-2008', 'davis-goadrich-2006', 'saito-2015', 'boyd-2013', 'flach-kull-2015'],
    lab: true,
  },
  {
    id: 'macro-micro', name: 'Médias macro, micro e ponderada', aka: ['multiclasse', 'multilabel', 'one-vs-rest'], group: 'curvas',
    formula: 'macro-F1 = (1/K) Σₖ F1ₖ\nmicro-F1 = F1(Σₖ TPₖ, Σₖ FPₖ, Σₖ FNₖ)',
    definition: 'Formas de agregar uma métrica binária em problemas com K classes: média das métricas por classe (macro) ou métrica das contagens somadas (micro).',
    intuition: 'Macro trata classes raras como tão importantes quanto as comuns; micro trata cada exemplo igual. Em single-label multiclasse, micro-F1 = acurácia.',
    origin: 'A distinção vem da avaliação de IR sobre várias consultas (Salton & McGill, 1983) e da categorização de textos; Sokolova & Lapalme (2009) sistematizam.',
    pitfalls: [
      'Existem duas definições de "macro-F1" (média dos F1 vs. F1 das médias de P e R) que dão números diferentes (Opitz & Burst, 2019).',
      'Em cross-validation, média por fold ≠ agregação das contagens (Forman & Scholz, 2010).',
    ],
    related: ['f-measure', 'acuracia-balanceada'],
    refIds: ['salton-mcgill-1983', 'sokolova-lapalme-2009', 'grandini-2020', 'forman-scholz-2010', 'hand-till-2001'],
  },
  {
    id: 'ranking-ir', name: 'Métricas de ranking (nDCG, bpref)', aka: ['DCG', 'precision@k', 'relevância graduada'], group: 'curvas',
    formula: 'DCG@k = Σᵢ₌₁ᵏ relᵢ / log₂(i + 1)\nnDCG@k = DCG@k / IDCG@k',
    definition: 'Quando a saída é uma lista ordenada, a posição importa. nDCG desconta relevância por posição e aceita relevância graduada; bpref lida com julgamentos incompletos.',
    intuition: 'Aqui a matriz de confusão vira uma matriz por corte k — e o gold standard precisa dizer "quão relevante", não só "relevante ou não".',
    origin: 'Järvelin & Kekäläinen (2002) propõem (n)DCG; Buckley & Voorhees (2004) criam bpref para coleções com julgamentos incompletos do TREC.',
    pitfalls: ['Coleções com pooling têm documentos relevantes não julgados; tratá-los como irrelevantes penaliza sistemas novos.'],
    related: ['curva-pr', 'gold-standard'],
    refIds: ['jarvelin-kekalainen-2002', 'buckley-voorhees-2004', 'voorhees-harman-2005', 'sanderson-2010', 'tague-sutcliffe-1992'],
  },

  // ——— Decisão ———
  {
    id: 'limiar-custo', name: 'Limiar ótimo e custos', aka: ['cost-sensitive', 'teoria bayesiana da decisão', 'função de perda'], group: 'decisao',
    formula: 'decida positivo se  p(y=1|x) ≥ c_FP / (c_FP + c_FN)\nno espaço do score:  LR(x) ≥ [(1 − π)·c_FP] / [π·c_FN]',
    definition: 'Com uma matriz de custos e probabilidades calibradas, o limiar que minimiza a perda esperada tem forma fechada.',
    intuition: '0,5 só é o limiar certo quando FP e FN custam o mesmo. Toda métrica de limiar embute, implicitamente, uma escolha de custos.',
    origin: 'Teoria estatística da decisão de Wald (1950); decisão bayesiana em Duda & Hart (1973) e Bishop (2006, §1.5); regra explícita para ML em Elkan (2001). Curvas de custo (Drummond & Holte, 2006) e a visão unificada de Hernández-Orallo, Flach & Ferri (2012) mostram métricas como perda esperada sob diferentes suposições de limiar.',
    pitfalls: ['A regra exige probabilidades calibradas; com scores descalibrados o limiar teórico erra.', 'Reamostrar para balancear classes muda a prevalência efetiva e, portanto, o limiar ótimo.'],
    related: ['calibracao', 'net-benefit', 'razao-verossimilhanca', 'roc'],
    refIds: ['wald-1950', 'duda-hart-stork-2001', 'bishop-2006', 'elkan-2001', 'drummond-holte-2006', 'hernandez-orallo-2012', 'murphy-2022'],
    lab: true,
  },
  {
    id: 'net-benefit', name: 'Benefício líquido e curva de decisão', aka: ['decision curve analysis', 'net benefit'], group: 'decisao',
    formula: 'NB(pₜ) = TP/N − (FP/N)·pₜ / (1 − pₜ)',
    definition: 'Utilidade clínica de usar o modelo com limiar pₜ, em unidades de "verdadeiros positivos líquidos", comparada a tratar todos ou ninguém.',
    intuition: 'O limiar pₜ expressa a troca aceitável entre FN e FP. A curva mostra para quais preferências o modelo vale mais que as estratégias triviais.',
    origin: 'Vickers & Elkin (2006). Adotado por Steyerberg (2019) e pelas diretrizes de validação de modelos clínicos.',
    pitfalls: ['Só faz sentido na faixa de limiares clinicamente plausíveis; olhar a curva inteira engana.'],
    related: ['limiar-custo', 'calibracao'],
    refIds: ['vickers-elkin-2006', 'steyerberg-2019', 'van-calster-2019'],
    lab: true,
  },
  {
    id: 'calibracao', name: 'Calibração', aka: ['reliability diagram', 'ECE', 'Platt', 'temperature scaling'], group: 'decisao',
    formula: 'ECE = Σ_b (|B_b|/N)·|acc(B_b) − conf(B_b)|',
    definition: 'Um modelo é calibrado se, entre os casos com probabilidade prevista 0,8, cerca de 80% são positivos.',
    intuition: 'Discriminação (AUC) e calibração são independentes: dá para ter AUC ótima e probabilidades inúteis. Qualquer uso do score como probabilidade — limiar por custo, benefício líquido — exige calibração.',
    origin: 'Verificação de previsões probabilísticas na meteorologia (Brier, 1950; Murphy & Winkler, 1987). No ML: Platt (1999), regressão isotônica (Zadrozny & Elkan, 2002), avaliação comparativa (Niculescu-Mizil & Caruana, 2005), ECE (Naeini et al., 2015), redes profundas superconfiantes (Guo et al., 2017).',
    pitfalls: [
      'ECE depende do número de bins e é enviesado.',
      'Calibração média ("calibration-in-the-large") pode esconder descalibração em subgrupos (Van Calster et al., 2019).',
    ],
    related: ['scoring-rules', 'limiar-custo', 'auc'],
    refIds: ['brier-1950', 'murphy-winkler-1987', 'platt-1999', 'zadrozny-elkan-2002', 'niculescu-caruana-2005', 'naeini-2015', 'guo-2017', 'kull-2017', 'kull-2019', 'van-calster-2019'],
  },
  {
    id: 'scoring-rules', name: 'Regras de pontuação próprias (Brier, log-loss)', aka: ['proper scoring rules', 'cross-entropy', 'Brier score'], group: 'decisao',
    formula: 'Brier = (1/N) Σᵢ (pᵢ − yᵢ)²\nLogLoss = −(1/N) Σᵢ [yᵢ log pᵢ + (1 − yᵢ) log(1 − pᵢ)]',
    definition: 'Métricas sobre a probabilidade prevista, não sobre a classe. "Próprias" significa que o valor esperado é otimizado ao reportar a probabilidade verdadeira.',
    intuition: 'A matriz de confusão descarta a confiança; regras próprias a avaliam. O Brier se decompõe em calibração + refinamento.',
    origin: 'Brier (1950) em meteorologia; teoria geral em Gneiting & Raftery (2007).',
    pitfalls: ['Log-loss é ilimitado: uma previsão confiante e errada domina a média.'],
    related: ['calibracao', 'limiar-custo'],
    refIds: ['brier-1950', 'gneiting-raftery-2007', 'murphy-winkler-1987', 'jolliffe-stephenson-2011'],
  },

  // ——— Validação ———
  {
    id: 'validacao-cruzada', name: 'Erro de teste e validação cruzada', aka: ['cross-validation', 'hold-out', 'bootstrap', 'nested CV'], group: 'validacao',
    formula: 'CV_k = (1/k) Σⱼ L(f₋ⱼ, Dⱼ)',
    definition: 'Estimar o desempenho em dados não vistos treinando e avaliando em partições disjuntas.',
    intuition: 'A matriz de confusão do treino mede memória; a do teste estima generalização. Qualquer decisão tomada olhando o teste (limiar, hiperparâmetro) contamina a estimativa.',
    origin: 'Stone (1974) formaliza; Efron & Tibshirani (1993) o bootstrap; Kohavi (1995) consolida 10-fold estratificado; Hastie, Tibshirani & Friedman (2009, cap. 7) dão o tratamento via bias-variance; Varma & Simon (2006) mostram o viés de selecionar e avaliar no mesmo CV.',
    pitfalls: ['Escolher hiperparâmetros e reportar no mesmo CV é otimista — use nested CV.', 'Folds não independentes (pacientes repetidos, séries temporais) inflam o resultado.'],
    related: ['comparacao-estatistica', 'benchmarks'],
    refIds: ['stone-1974', 'efron-tibshirani-1993', 'kohavi-1995', 'varma-simon-2006', 'esl-2009', 'isl-2021', 'raschka-2018'],
  },
  {
    id: 'comparacao-estatistica', name: 'Comparar classificadores', aka: ['McNemar', '5×2cv', 't corrigido', 'Friedman–Nemenyi', 'bayesiano'], group: 'validacao',
    formula: 't corrigido (Nadeau–Bengio): Var ≈ (1/k + n_teste/n_treino)·σ̂²',
    definition: 'Testes para decidir se a diferença de desempenho é maior do que a variação esperada por amostragem.',
    intuition: 'Folds de CV compartilham dados de treino, então as medidas não são independentes — o t-test ingênuo encontra diferenças que não existem.',
    origin: 'Dietterich (1998) compara testes aproximados; Nadeau & Bengio (2003) corrigem a variância; Demšar (2006) padroniza a comparação sobre vários datasets; Benavoli et al. (2017) propõem a alternativa bayesiana.',
    pitfalls: ['Significância estatística não é relevância prática; reporte tamanho de efeito e intervalo.', 'Comparar muitos modelos sem correção de múltiplas comparações.'],
    related: ['validacao-cruzada', 'auc'],
    refIds: ['dietterich-1998', 'nadeau-bengio-2003', 'demsar-2006', 'benavoli-2017', 'delong-1988', 'japkowicz-shah-2011'],
    widget: 'benchmark',
  },
  {
    id: 'rotulos-ruidosos', name: 'Rótulos sem gabarito confiável', aka: ['crowdsourcing', 'Dawid–Skene', 'classe latente', 'label noise'], group: 'validacao',
    definition: 'Métodos para estimar o rótulo verdadeiro e a matriz de confusão de cada anotador quando não existe um gold standard perfeito.',
    intuition: 'Cada anotador é um classificador com sua própria matriz de confusão. O gabarito é uma inferência, não um dado.',
    origin: 'Dawid & Skene (1979) com EM; em crowdsourcing, Snow et al. (2008) e Raykar et al. (2010); na medicina, modelos de classe latente (Rutjes et al., 2007).',
    pitfalls: ['Voto majoritário ignora que alguns anotadores são sistematicamente melhores.', 'Limpar rótulos do teste com o próprio modelo avaliado cria circularidade.'],
    related: ['gold-standard', 'kappa', 'benchmarks'],
    refIds: ['dawid-skene-1979', 'snow-2008', 'raykar-2010', 'rutjes-2007', 'northcutt-2021', 'pustejovsky-stubbs-2012'],
  },
  {
    id: 'benchmarks', name: 'Benchmarks e overfitting ao test set', aka: ['common task framework', 'leaderboard', 'distribution shift'], group: 'validacao',
    definition: 'Quando uma comunidade inteira otimiza contra o mesmo test set, o benchmark deixa de ser uma amostra independente.',
    intuition: 'O paradigma Cranfield funciona enquanto o test set representa a tarefa. Reuso repetido, erros de rótulo e seleção de datasets corroem essa suposição.',
    origin: 'Recht et al. (2019) recriam o test set do ImageNet e medem a queda; Liao et al. (2021) catalogam falhas de validade interna e externa; Dehghani et al. (2021) a "loteria dos benchmarks"; Kiela et al. (2021) propõem benchmarks dinâmicos; Paullada et al. (2021) criticam práticas de dados.',
    pitfalls: ['Ganhos de décimos de ponto em leaderboard muitas vezes estão dentro do erro de rótulo do próprio test set.'],
    related: ['gold-standard', 'validacao-cruzada', 'escolha-metrica'],
    refIds: ['cleverdon-1966', 'recht-2019', 'liao-2021', 'dehghani-2021', 'kiela-2021', 'paullada-2021', 'northcutt-2021'],
    widget: 'benchmark',
  },
  {
    id: 'escolha-metrica', name: 'Escolher a métrica pelo problema', aka: ['metrics reloaded', 'metric pitfalls', 'problem fingerprint'], group: 'validacao',
    definition: 'Não existe métrica universal: a escolha deve derivar da decisão que o sistema apoia, da prevalência, dos custos e da estrutura da saída.',
    intuition: 'Métricas discordam entre si porque respondem perguntas diferentes. Escolher a métrica é declarar o que importa.',
    origin: 'Ferri, Hernández-Orallo & Modroiu (2009) mostram empiricamente como métricas se agrupam; Hernández-Orallo et al. (2012) as unificam como perda esperada; Maier-Hein et al. (2024) e Reinke et al. (2024) criam um processo formal de recomendação e catálogo de armadilhas.',
    pitfalls: ['Escolher a métrica depois de ver os resultados.', 'Reportar uma única métrica quando stakeholders têm custos diferentes.'],
    related: ['limiar-custo', 'mcc', 'f-measure', 'auc'],
    refIds: ['maier-hein-2024', 'reinke-2024', 'ferri-2009', 'hernandez-orallo-2012', 'sokolova-lapalme-2009', 'japkowicz-shah-2011'],
  },
]

/** Conceitos adicionados depois (inferência, dados) ficam em extra.json para facilitar contribuições. */
export const CONCEPTS: Concept[] = [...BASE_CONCEPTS, ...(extra as Concept[])]
